export type Location = { id: string; name: string; lat: number; lng: number };
export type User = {
  id: string;
  name: string;
  email: string;
  phone: string;
  address: string;
  location_id: string;
  role: 'customer' | 'admin' | 'outlet' | 'rider';
  login_id?: string;
  active: number;
};
export type Product = {
  id: string;
  outlet_id: string;
  outlet_name: string;
  name: string;
  description: string;
  category: string;
  price: number;
  effective_price: number;
  stock: number;
  unit: string;
  location_id: string;
  discount: number;
  deal: string;
  images: string[];
  includes: string;
  excludes: string;
  delivery_minutes: number;
  active: number;
};
export type Outlet = {
  id: string;
  name: string;
  phone: string;
  email?: string;
  address: string;
  location_id: string;
  image: string;
  category: string;
  customer_id?: string;
  lat: number;
  lng: number;
  active: number;
};
export type CartItem = { product: Product; quantity: number };
export type Order = {
  id: string;
  reference: string;
  user_id: string | null;
  outlet_id: string;
  rider_id: string | null;
  name: string;
  email: string;
  phone: string;
  address: string;
  location_id: string;
  lat: number;
  lng: number;
  notes: string;
  payment_method: string;
  subtotal: number;
  delivery_fee: number;
  total: number;
  status: string;
  otp?: string;
  created_at: string;
  deliver_by: string;
  delivered_at: string | null;
  outlet: { name: string; address: string; lat: number; lng: number; phone: string };
  rider: { name: string; phone: string } | null;
  items: { id: string; name: string; quantity: number; unit_price: number; image: string }[];
  events: { status: string; created_at: string }[];
};
export type Ad = {
  title: string;
  description: string;
  label: string;
  link: string;
  image: string;
  active: boolean;
};
